spring:
  application:
    name: GlassTimer
  datasource:
    url: jdbc:postgresql://localhost:5432/quizdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # change to validate in prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

quiz:
  timer:
    duration-seconds: 900

jwt:
  secret: your-secret-key-here-make-it-at-least-256-bits-long-for-security
  expiration: 86400000  # 24 hours in milliseconds

server:
  port: 8080